apiVersion: bigquery.cnrm.cloud.google.com/v1alpha1
kind: BigQueryDataset
metadata:
  name: example-bigquerydataset
spec:
  defaultTableExpirationMs: "3600000"
  description: "BigQuery Dataset Example"
  friendlyName: example-bigquerydataset
