apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      volumes:
        - emptyDir: {}
          name: search-log
        - name: gcp-gcs-writer-sa-key
          secret:
            defaultMode: 420
            items:
              - key: key-content
                path: key-content
            secretName: gcp-gcs-writer-sa-key
      containers:
        - name: example
          image: example:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: YOURKIT_OPTS
            value: -agentpath:/yourkit/lib/libyjpagent.so=sampling,port=10001,listen=all,logdir=/var/log/search/yourkit,onexit=snapshot,dir=/var/log/search/yourkit
          - name: CLOUDSDK_CONFIG
            value: /tmp/gcloud
          - name: BOTO_CONFIG
            value: /tmp/gcloud/.boto
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /search/.gcp-gcs-writer-sa-key/key-content
          command:
            - /search/dist/run.sh
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /var/log/search
              name: search-log
            - mountPath: /search/.gcp-gcs-writer-sa-key
              name: gcp-gcs-writer-sa-key
              readOnly: true