apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
  name: example-service
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: example
  type: ClusterIP
