apiVersion: storage.cnrm.cloud.google.com/v1alpha1
kind: StorageBucket
metadata:
  name: cnrm-eap-cnrm-gcpnext19-demo-example
spec:
  lifecycle:
    rules:
      - action:
          type: Delete
        condition:
          age: 7
